# Generated by Django 4.2.30 on 2026-07-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='RentEase', max_length=200)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('default_grace_hours', models.PositiveIntegerField(default=2)),
                ('default_late_fee_per_hour', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Organization settings',
            },
        ),
    ]
