# Generated by Django 4.2.30 on 2026-07-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('quotation', 'Quotation'), ('quotation_sent', 'Quotation Sent'), ('reserved', 'Reserved'), ('picked_up', 'Picked Up'), ('late_pickup', 'Late Pickup'), ('returned', 'Returned'), ('late_return', 'Late Return'), ('cancelled', 'Cancelled')], default='quotation', max_length=20)),
                ('invoice_status', models.CharField(choices=[('nothing_to_invoice', 'Nothing to Invoice'), ('quotation_sent', 'Quotation Sent'), ('invoiced', 'Invoiced')], default='nothing_to_invoice', max_length=20)),
                ('pickup_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('standard_delivery', 'Standard Delivery'), ('store_pickup', 'Store Pickup')], default='store_pickup', max_length=20)),
                ('untaxed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit_held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='accounts.customeraddress')),
                ('invoice_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_orders', to='accounts.customeraddress')),
                ('pricelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.pricelist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='Units', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rentals.rentalorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.product')),
            ],
        ),
    ]
